### ISSUE TITLE
Completed file

### ISSUE THREAD

**Issue by IndianaTones** [languageislands/heathdogon#5]
Dumb question here, but how do I see the full dataset now which has the concepts and the forms in one file?

**Comment by IndianaTones** [comment]
Just coming back to this:

$ edictor wordlist --name=heathdogon --addon="concept_pos:pos"

only makes a blank column pos

**Comment by chrzyki** [comment]
> Just coming back to this @chrzyki ?
> 
> $ edictor wordlist --name=heathdogon --addon="concept_pos:pos"
> 
> only makes a blank column pos

Hey Abby,

sorry for the long response time. Please try:

```Bash
edictor wordlist --name=heathdogon --data=cldf/cldf-metadata.json --addon=concept_partofspeech:pos
```

That should work.

**Comment by IndianaTones** [comment]
Yes that did it!  Now, if I want to add more columns, such as the Concepticon Concept (the current Concept column actually contains the gloss) do I add those to the same --addon or add additional lines for each column?

**Comment by chrzyki** [comment]
> Yes that did it! Now, if I want to add more columns, such as the Concepticon Concept (the current Concept column actually contains the gloss) do I add those to the same --addon or add additional lines for each column?

You can add comma-separated columns that you'd like to include to the same call to `--addon`, i.e.:

```
edictor wordlist --name=heathdogon --data=cldf/cldf-metadata.json --addon=concept_partofspeech:pos,concept_concepticon_gloss:concepticon_gloss
```

(Read the parameters for `--addon` as: Take from the parameters/concept table the column called `partofspeech` and add it as a separate column with the column title `pos`, additionally, take from the parameters/concept table the column called `concepticon_gloss` and add it as a separate column with the column title `concepticon_gloss` etc.)

**Comment by IndianaTones** [comment]
That's exactly what I was looking for. Much appreciated. In the future, other than the --help command, is there documentation for these options anywhere? You mention reading the parameters...

**Comment by chrzyki** [comment]
Sorry, that was more a 'read the following as in it meaning xyz'. :)

I suppose the [CALC blog](https://calc.hypotheses.org/?s=edictor) is a good resource for more documentation and usage-samples for EDICTOR/pyedictor.
